# Generated by Django 5.2 on 2025-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description_short", models.TextField(verbose_name="Описание")),
                ("description_long", models.TextField(verbose_name="Подробности")),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lon", models.FloatField(verbose_name="Долгота")),
            ],
            options={
                "verbose_name": "place",
                "verbose_name_plural": "places",
                "ordering": ["title"],
            },
        ),
    ]
