# Generated by Django 5.2 on 2025-11-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="lon",
            new_name="lng",
        ),
    ]
