# Generated by Django 5.2 on 2025-11-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_placeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["title"],
                "verbose_name": "место",
                "verbose_name_plural": "места",
            },
        ),
    ]
