# Generated by Django 5.2 on 2025-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_place_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={"ordering": ["-order"]},
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(upload_to="media", verbose_name="Изображение"),
        ),
    ]
