# Generated by Django 5.2 on 2025-11-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_placeimage_options_alter_placeimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="place_id",
            field=models.SlugField(
                blank=True,
                help_text="Латинские буквы, цифры и подчеркивания",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Уникальный идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=models.TextField(verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(verbose_name="Краткое описание"),
        ),
    ]
