# Generated by Django 5.2 on 2025-11-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_place_place_id_alter_place_description_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_id",
            field=models.SlugField(
                help_text="Латинские буквы, цифры и подчеркивания",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Уникальный идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Изображение"),
        ),
    ]
