# Generated by Django 5.2 on 2025-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_alter_place_place_id_alter_placeimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["-order"],
                "verbose_name": "фотография",
                "verbose_name_plural": "фотографии",
            },
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Позиция"),
        ),
    ]
