# Generated by Django 5.2 on 2025-11-16 12:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_placeimage_options_alter_placeimage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
    ]
