# Generated by Django 5.2 on 2025-11-17 17:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_place_description_long"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="place",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="place",
            name="place_id",
        ),
        migrations.AddField(
            model_name="place",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AddField(
            model_name="place",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
    ]
