# Generated by Django 5.2 on 2025-11-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_remove_place_description_long_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["order"],
                "verbose_name": "фотография",
                "verbose_name_plural": "фотографии",
            },
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
                verbose_name="Место",
            ),
        ),
        migrations.AddIndex(
            model_name="placeimage",
            index=models.Index(
                fields=["place", "order"], name="places_plac_place_i_132bbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placeimage",
            index=models.Index(fields=["order"], name="order_idx"),
        ),
    ]
