# Generated by Django 5.2 on 2025-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_alter_placeimage_options_alter_placeimage_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
    ]
